Repository ManageIQ/manageiq-pods, pull requests merged in 2018-08, with the labels that each got.

#297 [Changelog] Update for Sprint 89
  CHANGELOG.md
Labels: documentation

#300 Use the new repmgr preload library name
  templates/miq-template.yaml
Labels: enhancement, hammer/yes

#301 [HAMMER] Changed template to add miq-log config map
  templates/miq-template.yaml
Labels: bug, gaprindashvili/no, template

#302 [Changelog] Update for Sprint 93
  CHANGELOG.md
Labels: documentation

#303 Add a simple script to deploy MIQ on minishift
  bin/deploy_on_minishift
Labels: enhancement, hammer/yes
