Repository ManageIQ/manageiq-pods, pull requests merged in 2018-09, with the labels that each got.

#304 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#305 [HAMMER] Use the ruby 2.4 image
  images/miq-app/Dockerfile
Labels: enhancement

#307 [HAMMER] Make builds work
  images/miq-app-frontend/Dockerfile
  images/miq-app/Dockerfile
Labels: bug

#309 [HAMMER] Remove the logrotate configmap in the teardown script
  teardown
Labels: cleanup

#310 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation
