Repository ManageIQ/manageiq-pods, pull requests merged in 2018-03, with the labels that each got.

#274 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#275 Remove 'docker' references
  README.md
  images/manageiq-base-worker/Dockerfile
  images/manageiq-base-worker/container-assets/entrypoint
  images/manageiq-base-worker/container-assets/manageiq_liveness_check
  images/manageiq-base/Dockerfile
  images/manageiq-base/container-assets/container-scripts/container-deploy-common.sh
  images/manageiq-base/container-assets/container-scripts/post-upgrade
  images/manageiq-base/container-assets/container-scripts/pre-upgrade
  images/manageiq-orchestrator/Dockerfile
  images/manageiq-orchestrator/container-assets/appliance-initialize.sh
  images/manageiq-orchestrator/container-assets/check-dependent-services.sh
  images/manageiq-orchestrator/container-assets/entrypoint
  images/manageiq-ui-worker/Dockerfile
  images/manageiq-ui-worker/container-assets/manageiq-http.conf
  templates/miq-template-ext-db.yaml
  templates/miq-template.yaml
Labels: cleanup, gaprindashvili/no

#278 [GAPRINDASHVILI] Fix container logrotate
  images/miq-app/Dockerfile
  images/miq-app/container-assets/miq_logs.conf
Labels: bug
