Repository ManageIQ/manageiq-pods, pull requests merged in 2018-12, with the labels that each got.

#317 Bump master travis.yml to ruby 2.3.8.
  .travis.yml
Labels: changelog/no, gaprindashvili/yes, hammer/yes

#318 [GAPRINDASHVILI] Update to ruby 2.3.8
  images/miq-app/Dockerfile
Labels: enhancement

#319 Bump master travis.yml to ruby 2.4.5
  .travis.yml
Labels: test
