Repository ManageIQ/manageiq-pods, pull requests merged in 2019-11, with the labels that each got.

#342 Quality of life update for new architecture
  README.md
  bin/deploy
  bin/teardown
  build_all.sh
  images/manageiq-base-worker/container-assets/entrypoint
  images/manageiq-base/Dockerfile
  images/manageiq-base/container-assets/container-scripts/container-deploy-common.sh
  images/manageiq-base/container-assets/container-scripts/post-upgrade
  images/manageiq-base/container-assets/container-scripts/pre-upgrade
  images/manageiq-base/container-assets/container_env
  images/manageiq-orchestrator/Dockerfile
  images/manageiq-orchestrator/container-assets/appliance-initialize.sh
  images/manageiq-orchestrator/container-assets/check-dependent-services.sh
  images/manageiq-orchestrator/container-assets/entrypoint
  parameters
  templates/app/manageiq-secrets.yaml
  templates/app/orchestrator.yaml
  templates/app/postgresql-secrets.yaml
  templates/app/postgresql.yaml
  templates/app/secrets.yaml
  templates/helpers/build-template.yaml
  templates/helpers/miq-scc-sysadmin.yaml
  templates/miq-template-ext-db.yaml
Labels: enhancement, technical debt

#347 [IVANCHUK] Template removal of pg shared_preload_librariers
  templates/miq-template.yaml
Labels: bug

#348 Use kubernetes compatible objects
  README.md
  bin/deploy
  bin/teardown
  templates/app/httpd.yaml
  templates/app/memcached.yaml
  templates/app/orchestrator.yaml
  templates/app/postgresql.yaml
  templates/app/rbac.yaml
  templates/examples/minikube-pv.yaml
Labels: enhancement
