Repository ManageIQ/manageiq-pods, pull requests merged in 2019-08, with the labels that each got.

#326 Update ruby, node and postgresql
  images/miq-app-frontend/Dockerfile
  images/miq-app/Dockerfile
Labels: ivanchuk/yes

#328 [Changelog] Update for Sprint 117
  CHANGELOG.md
Labels: documentation

#329 [Changelog] Update for Ivanchuk Beta2
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#330 Set IMAGE_REF
  images/miq-app-frontend/Dockerfile
Labels: hammer/yes, ivanchuk/yes
