Repository ManageIQ/manageiq-pods, pull requests merged in 2019-05, with the labels that each got.

#323 Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: changelog/no, test

#324 Add BUILD file
  images/miq-app/Dockerfile
Labels: hammer/yes

#325 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test
