Repository ManageIQ/manageiq-pods, pull requests merged in 2019-10, with the labels that each got.

#333 Switch find_by_* to lookup_by_*
  images/miq-app/container-assets/container-scripts/container-deploy-common.sh
Labels: ivanchuk/no, refactoring

#335 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: changelog/no, test

#336 Use the PG 10 image rather than our custom one.
  templates/miq-template.yaml
Labels: enhancement

#338 Fix dump and restore specs
  .gitignore
  templates/app/httpd.yaml
  templates/app/memcached.yaml
  templates/app/orchestrator.yaml
  templates/app/postgresql.yaml
  templates/app/secrets.yaml
  templates/build-template.yaml
Labels: test

#341 Use the correct args when writing the BUILD file in the base image
  images/manageiq-base/Dockerfile
Labels: bug
