Repository ManageIQ/manageiq-pods, pull requests merged in 2020-02, with the labels that each got.

#357 Changes for adding ppc64le support
  bin/build
  images/manageiq-base/Dockerfile
  images/manageiq-ui-worker/Dockerfile
Labels: enhancement, unmergeable

#368 Remove the MY_POD_NAMESPACE env var from the orchestrator
  templates/app/orchestrator.yaml
Labels: technical debt, template

#367 Use multi-stage builds to remove need for secrets container
  bin/build
  images/manageiq-base/Dockerfile
Labels: enhancement

#369 Allow for changing the app name using a parameter
  README.md
  bin/deploy
  parameters
  templates/app/app-secrets.yaml
  templates/app/httpd.yaml
  templates/app/memcached.yaml
  templates/app/orchestrator.yaml
  templates/app/postgresql-secrets.yaml
  templates/app/postgresql.yaml
  templates/app/rbac.yaml
Labels: enhancement

#370 Add IMAGE_PULL_SECRET parameter
  parameters
  templates/app/orchestrator.yaml
Labels: enhancement

#372 Base images on ubi8
  images/manageiq-base/Dockerfile
  images/manageiq-ui-worker/Dockerfile
Labels: enhancement
