Repository ManageIQ/manageiq-pods, pull requests merged in 2020-07, with the labels that each got.

#566 Add reconcile functions to Kafka and Zookeeper
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/kafka.go
Labels: enhancement, operator

#567 Fixed typo in the description for httpdAuthConfig
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
Labels: bug, documentation, jansa/yes?

#568 Fix typo in log message
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
Labels: bug

#569 Allow orchestrator to be updated during reconcile
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Labels: enhancement, operator

#570 Move the rbac functions into their component source files
  manageiq-operator/pkg/helpers/miq-components/httpd.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
  manageiq-operator/pkg/helpers/miq-components/rbac.go
Labels: operator, refactoring

#532 Add a flag to gate worker resource constraints
  images/manageiq-orchestrator/container-assets/entrypoint
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Labels: enhancement, jansa/yes?, operator

#575 Use the CR's UID rather than generating a new one for the orchestrator
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Labels: bug

#577 Prevent the reconcile loop from updating the services on every run
  manageiq-operator/pkg/helpers/miq-components/kafka.go
  manageiq-operator/pkg/helpers/miq-components/memcached.go
  manageiq-operator/pkg/helpers/miq-components/postgresql.go
Labels: enhancement

#572 Allow httpd Services, Deployment and ConfigMap to be reconciled
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: enhancement

#578 Dont log unchanged results
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
Labels: enhancement

#579 Use a service account for pull secrets
  manageiq-operator/go.mod
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
  manageiq-operator/pkg/helpers/miq-components/kafka.go
  manageiq-operator/pkg/helpers/miq-components/memcached.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
  manageiq-operator/pkg/helpers/miq-components/postgresql.go
  manageiq-operator/pkg/helpers/miq-components/rbac.go
Labels: enhancement, jansa/conflict, operator

#580 [JANSA] Use a service account for pull secrets
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
  manageiq-operator/pkg/helpers/miq-components/kafka.go
  manageiq-operator/pkg/helpers/miq-components/memcached.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
  manageiq-operator/pkg/helpers/miq-components/postgresql.go
  manageiq-operator/pkg/helpers/miq-components/rbac.go
Labels: enhancement, operator

#581 Fix missing label for selector
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: bug, operator

#571 Enhancement to optionally fetch the OIDCAuthIntrospectionURL
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: enhancement

#582 [JANSA] Enhancement to optionally fetch the OIDCAuthIntrospectionURL from the Provider
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: enhancement

#588 adding package update command
  images/manageiq-base/Dockerfile
Labels: bug, jansa/yes?

#589 Add operator bundle instructions to README
  manageiq-operator/README.md
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml
Labels: documentation

#593 Fix incorrect command in operator README
  manageiq-operator/README.md
Labels: bug, documentation

#594 Update code owners
  CODEOWNERS
Labels: developer

#597 Do not add nightly yum repo in release build
  bin/build
  images/manageiq-base/Dockerfile
Labels: bug, jansa/yes?

#600 [JANSA] We should default to jansa, not master
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
Labels: bug
