Repository ManageIQ/manageiq-pods, pull requests merged in 2020-09, with the labels that each got.

#618 Add OIDCCacheShmEntrySizeMax parameter
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Labels: bug

#621 Add ability to skip operator build
  bin/build
Labels: enhancement

#626 Add backup annotations for velero
  manageiq-operator/pkg/helpers/miq-components/kafka.go
  manageiq-operator/pkg/helpers/miq-components/postgresql.go
  manageiq-operator/pkg/helpers/miq-components/util.go
Labels: enhancement

#627 [JANSA] Install ovirt packages before ansible venv packages
  images/manageiq-base/Dockerfile
Labels: bug

#628 Manage the CR and include it in the reconcile loop
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/cr.go
Labels: enhancement

#629 Fix typo of key name in example
  manageiq-operator/README.md
Labels: bug, documentation

#631 Add ManageIQ as the provider of the upstream operator
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml
Labels: bug
