Repository ManageIQ/manageiq-pods, pull requests merged in 2020-01, with the labels that each got.

#363 Remove the DISABLE_MIQ_WORKER_HEARTBEAT env var
  images/manageiq-base-worker/container-assets/entrypoint
Labels: bug

#364 Enable heartbeat more
  images/manageiq-base-worker/container-assets/entrypoint
Labels: bug

#362 Add support for github enterprise
  bin/build
  images/manageiq-base/Dockerfile
Labels: enhancement

#365 Add a script to remove all images for a tag
  bin/remove_images
Labels: enhancement

#366 Create the ui, api, and remote console services in templates
  templates/app/httpd.yaml
Labels: cleanup, template
