Repository ManageIQ/manageiq-pods, pull requests merged in 2020-08, with the labels that each got.

#603 Fixed typo in the httpd component.
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: bug

#606 Use standard token introspection endpoint
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: bug, jansa/yes?

#611 [IVANCHUK] Bundle with qpid-proton
  images/miq-app/Dockerfile
Labels: bug

#613 [IVANCHUK] Properly reset HTTPD headers
  templates/miq-template-ext-db.yaml
  templates/miq-template.yaml
Labels: bug

#604 Do not bring up the PostgreSQL or Kafka/Zookeeper services if specifying external services
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
Labels: enhancement

#608 Enhance the README and add a description for deploying with OIDC
  manageiq-operator/README.md
Labels: enhancement

#617 Add instructions for Configuring OpenID-Connect with a CA Certificate
  manageiq-operator/README.md
Labels: enhancement
