Repository ManageIQ/manageiq-pods, pull requests merged in 2020-12, with the labels that each got.

#656 Drop the old templates since the operator is stable
  README.md
  templates/app/app-secrets.yaml
  templates/app/httpd.yaml
  templates/app/kafka-secrets.yaml
  templates/app/kafka.yaml
  templates/app/memcached.yaml
  templates/app/orchestrator.yaml
  templates/app/postgresql-secrets.yaml
  templates/app/postgresql.yaml
  templates/app/rbac.yaml
  templates/examples/minikube-pv.yaml
  templates/examples/miq-pv-backup-example.yaml
  templates/examples/miq-pv-db-example.yaml
  templates/helpers/miq-scc-sysadmin.yaml
  templates/ops/miq-backup-job.yaml
  templates/ops/miq-restore-job.yaml
Labels: technical debt

#657 Add permissions to our role for Network Policies
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml
  manageiq-operator/deploy/role.yaml
Labels: bug

#660 Update to UBI/CentOS 8.3
  images/manageiq-base/Dockerfile
Labels: jansa/yes?, kasparov/yes?

#655 Set the TLS certificate CN to the application domain
  manageiq-operator/pkg/helpers/miq-components/httpd.go
  manageiq-operator/pkg/helpers/tlstools/generate_crt.go
Labels: bug

#661 Update to UBI 8.3 #2
  images/manageiq-base/Dockerfile
Labels: jansa/yes?, kasparov/yes?

#662 Add debug logging for the reconcile loop
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
Labels: enhancement

#663 Exclude net-snmp* packages from ubi repo
  images/manageiq-base/Dockerfile
Labels: bug, jansa/yes?, kasparov/yes?
