Repository ManageIQ/manageiq-pods, pull requests merged in 2020-03, with the labels that each got.

#375 Add glibc-langpack-en to solve locale issues
  images/manageiq-base/Dockerfile
Labels: bug

#377 Update Dockerfile for GIT_AUTH
  images/manageiq-base/Dockerfile
Labels: bug

#380 Use nodejs:12 from AppStream
  bin/build
  images/manageiq-base/Dockerfile
Labels: enhancement, jansa/yes?

#385 Pull latest ubi8 image for build
  bin/build
Labels: enhancement

#382 Align package list with appliance
  bin/build
  images/manageiq-base/Dockerfile
Labels: enhancement, jansa/yes?

#378 Change the postgres image tag from latest to 10
  parameters
  templates/app/postgresql.yaml
  templates/ops/miq-backup-job.yaml
  templates/ops/miq-restore-job.yaml
Labels: enhancement

#386 Update to ruby 2.6
  images/manageiq-base/Dockerfile
Labels: enhancement, jansa/yes?

#387 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#388 Add a hooks url for build-time customization
  bin/build
  images/manageiq-base/Dockerfile
Labels: enhancement

#389 added operator for manageiq-pods
  .gitignore
  manageiq-operator/Gopkg.lock
  manageiq-operator/Gopkg.toml
  manageiq-operator/README.md
  manageiq-operator/build/Dockerfile
  manageiq-operator/build/bin/entrypoint
  manageiq-operator/build/bin/user_setup
  manageiq-operator/cmd/manager/main.go
  manageiq-operator/deploy/crds/manageiq_v1alpha1_manageiq_cr.yaml
  manageiq-operator/deploy/crds/manageiq_v1alpha1_manageiq_crd.yaml
  manageiq-operator/deploy/operator.yaml
  manageiq-operator/deploy/role.yaml
  manageiq-operator/deploy/role_binding.yaml
  manageiq-operator/deploy/service_account.yaml
  manageiq-operator/pkg/apis/addtoscheme_manageiq_v1alpha1.go
  manageiq-operator/pkg/apis/apis.go
  manageiq-operator/pkg/apis/manageiq/v1alpha1/doc.go
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/apis/manageiq/v1alpha1/register.go
  manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go
  manageiq-operator/pkg/controller/add_manageiq.go
  manageiq-operator/pkg/controller/controller.go
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/httpd_conf/application.conf
  manageiq-operator/pkg/helpers/httpd_conf/auth-configuration.conf
  manageiq-operator/pkg/helpers/httpd_conf/authentication.conf
  manageiq-operator/pkg/helpers/httpd_conf/configuration-active-directory-auth
  manageiq-operator/pkg/helpers/httpd_conf/configuration-external-auth
  manageiq-operator/pkg/helpers/httpd_conf/configuration-internal-auth
  manageiq-operator/pkg/helpers/httpd_conf/configuration-openid-connect-auth
  manageiq-operator/pkg/helpers/httpd_conf/configuration-saml-auth
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-application-api-conf
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-load-modules-conf
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-login-form-conf
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-lookup-user-details-conf
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-openid-connect-remote-user-conf
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-remote-user-conf
  manageiq-operator/pkg/helpers/miq-components/app-secret.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
  manageiq-operator/pkg/helpers/miq-components/memcached.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
  manageiq-operator/pkg/helpers/miq-components/postgresql-secrets.go
  manageiq-operator/pkg/helpers/miq-components/postgresql.go
  manageiq-operator/pkg/helpers/miq-components/rbac.go
  manageiq-operator/pkg/helpers/postgresql_conf/01_miq_overrides.conf
  manageiq-operator/pkg/helpers/randstring/randstring.go
  manageiq-operator/pkg/helpers/tlstools/generate_crt.go
  manageiq-operator/version/version.go
Labels: enhancement

#390 Add kafka for messaging
  bin/deploy
  parameters
  templates/app/kafka-secrets.yaml
  templates/app/kafka.yaml
  templates/app/orchestrator.yaml
Labels: enhancement, jansa/yes?

#393 Fix the backup and restore jobs
  README.md
  templates/ops/miq-backup-job.yaml
  templates/ops/miq-backup-pvc.yaml
  templates/ops/miq-restore-job.yaml
Labels: bug, jansa/yes?

#395 Add gofmt to CI
  .travis.yml
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/controller/controller.go
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
Labels: test

#396 Add travis badge
  README.md
Labels: documentation

#397 Use manageiq image for restore job
  templates/ops/miq-restore-job.yaml
Labels: bug, jansa/yes?

#398 Remove trailing whitespace and add end of file newlines
  manageiq-operator/README.md
  manageiq-operator/pkg/helpers/httpd_conf/authentication.conf
  manageiq-operator/pkg/helpers/httpd_conf/configuration-active-directory-auth
  manageiq-operator/pkg/helpers/httpd_conf/configuration-external-auth
  manageiq-operator/pkg/helpers/httpd_conf/configuration-internal-auth
  manageiq-operator/pkg/helpers/httpd_conf/configuration-openid-connect-auth
  manageiq-operator/pkg/helpers/httpd_conf/configuration-saml-auth
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-application-api-conf
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-load-modules-conf
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-login-form-conf
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-lookup-user-details-conf
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-openid-connect-remote-user-conf
  manageiq-operator/pkg/helpers/httpd_conf/external-auth-remote-user-conf
  manageiq-operator/pkg/helpers/postgresql_conf/01_miq_overrides.conf
Labels: cleanup

#413 Request only the permissions we need and make the operator work
  manageiq-operator/deploy/role.yaml
Labels: bug, jansa/yes?

#412 Add build step to Travis
  .travis.yml
Labels: test
