Repository ManageIQ/manageiq-pods, pull requests merged in 2020-11, with the labels that each got.

#648 Exclude RHEL 8.3 packages that conflict with CentOS 8.2
  images/manageiq-base/Dockerfile
Labels: bug, jansa/yes?, kasparov/yes?

#651 Pass pod hostname as system-uid option to run_single_worker.rb
  .travis.yml
  images/manageiq-base-worker/container-assets/entrypoint
Labels: enhancement, kasparov/yes?

#653 Prefer recreate as the deployment strategy for many services.
  manageiq-operator/pkg/helpers/miq-components/httpd.go
  manageiq-operator/pkg/helpers/miq-components/kafka.go
  manageiq-operator/pkg/helpers/miq-components/memcached.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
  manageiq-operator/pkg/helpers/miq-components/postgresql.go
Labels: bug

#654 Attempt to pull server GUID from existing orchestrator if one exists
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/cr.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Labels: enhancement, kasparov/yes

#649 Add Ingress Network Policies to the operator
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/network_policies.go
Labels: enhancement
