Repository ManageIQ/manageiq-pods, pull requests merged in 2020-10, with the labels that each got.

#619 Add velero-backup label to important resources that need to be backed up
  manageiq-operator/README.md
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/app-secret.go
  manageiq-operator/pkg/helpers/miq-components/cr.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
  manageiq-operator/pkg/helpers/miq-components/kafka.go
  manageiq-operator/pkg/helpers/miq-components/operator.go
  manageiq-operator/pkg/helpers/miq-components/postgresql.go
  manageiq-operator/pkg/helpers/miq-components/rbac.go
  manageiq-operator/pkg/helpers/miq-components/util.go
Labels: enhancement

#639 Skip reconciling the OIDC Client Secret if one isn't specified
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
Labels: bug

#647 Document allowing manageiq images in kubernetes
  README.md
Labels: documentation
