Repository ManageIQ/manageiq-pods, pull requests merged in 2021-01, with the labels that each got.

#666 Add simple installation process for the VMware VDDK
  .gitignore
  README.md
  images/manageiq-base-worker/Dockerfile
  images/manageiq-base-worker/container-assets/extract-vmware-vddk
  images/manageiq-base-worker/container-assets/install-vmware-vddk
Labels: enhancement

#667 [IVANCHUK] Lock bundler to v2.1.4
  images/miq-app/Dockerfile
Labels: bug

#669 Pull the latest base image for operator build
  bin/build
Labels: jansa/yes?, kasparov/yes?
