Repository ManageIQ/manageiq-pods, pull requests merged in 2021-05, with the labels that each got.

#712 remove unnecessary headers
  images/manageiq-ui-worker/container-assets/manageiq-http.conf
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Labels: enhancement

#716 Omit any empty fields in the ManageIQSpec
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go
Labels: enhancement

#714 Sort alphabetically and fix inconsistent whitespace
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go
Labels: developer

#717 Switch from postgresql.crt to root.crt
  images/manageiq-base/container-assets/container_env
Labels: bug

#718 Upgrade operator-sdk to v0.17
  .travis.yml
  manageiq-operator/cmd/manager/main.go
  manageiq-operator/deploy/olm-catalog/manageiq-operator/manifests/manageiq-operator.clusterserviceversion.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/manifests/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/go.mod
  manageiq-operator/go.sum
Labels: enhancement

#719 External postgres doc added to the official documentation
  manageiq-operator/README.md
Labels: documentation
