Repository ManageIQ/manageiq-pods, pull requests merged in 2021-04, with the labels that each got.

#705 Added labels to image build to address red hat certification failures on application image
  manageiq-operator/build/Dockerfile
Labels: technical debt

#708 Ensure worker image env vars are updated during reconcile
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Labels: enhancement, lasker/yes?

#709 Update orchestrator image
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Labels: enhancement, lasker/yes?

#710 Reconcile Orchestrator ENV vars
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Labels: bug, lasker/yes?

#711 Add backup labels to the PVCs
  manageiq-operator/pkg/helpers/miq-components/kafka.go
  manageiq-operator/pkg/helpers/miq-components/postgresql.go
Labels: enhancement
