Repository ManageIQ/manageiq-pods, pull requests merged in 2021-02, with the labels that each got.

#670 Switch NetworkPolicies from extensions/v1beta1 to networking/v1
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml
  manageiq-operator/deploy/role.yaml
  manageiq-operator/pkg/helpers/miq-components/network_policies.go
Labels: bug

#674 Support Postgres with SSL certificates
  images/manageiq-base/container-assets/container_env
  manageiq-operator/README.md
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
  manageiq-operator/pkg/helpers/miq-components/postgresql.go
Labels: enhancement

#679 Backup and restore documentation has moved to manageiq-documentation
  manageiq-operator/README.md
Labels: technical debt

#664 Attempt to default the image pull secret
  manageiq-operator/README.md
  manageiq-operator/pkg/helpers/miq-components/cr.go
Labels: enhancement

#681 Limit the scope of the default-deny network policy
  manageiq-operator/pkg/helpers/miq-components/network_policies.go
Labels: enhancement

#683 Remove no longer used HOOKS_SCRIPT_URL
  bin/build
  images/manageiq-base/Dockerfile
Labels: technical debt

#680 Adding support for optional Image References
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/helpers/miq-components/cr.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
  manageiq-operator/pkg/helpers/miq-components/kafka.go
  manageiq-operator/pkg/helpers/miq-components/memcached.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
  manageiq-operator/pkg/helpers/miq-components/postgresql.go
Labels: enhancement

#677 Added support for AppAnnotations
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
  manageiq-operator/pkg/helpers/miq-components/kafka.go
  manageiq-operator/pkg/helpers/miq-components/memcached.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
  manageiq-operator/pkg/helpers/miq-components/postgresql.go
  manageiq-operator/pkg/helpers/miq-components/util.go
Labels: enhancement

#684 Only allow valid authentication types in the CRs
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/cr.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: cleanup

#686 Exclude dracut from ubi8 repo to avoid conflicts
  images/manageiq-base/Dockerfile
Labels: bug, jansa/yes?, kasparov/yes?

#685 Enhance Operator documentation
  manageiq-operator/README.md
Labels: documentation, enhancement, operator

#687 We only need the ruby environment, not full container_env
  images/manageiq-base-worker/container-assets/manageiq_liveness_check
Labels: enhancement, performance

#688 Fasterer liveness check
  images/manageiq-base-worker/container-assets/manageiq_liveness_check
Labels: lasker/yes?, performance

#671 Added support for Managed OIDC Configurations
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: enhancement
