Repository ManageIQ/manageiq-pods, pull requests merged in 2021-06, with the labels that each got.

#721 Update base image to UBI 8.4, change appliance_build stage to latest
  images/manageiq-base/Dockerfile
Labels: dependencies

#722 Prefer Perl from the CentOS appstream rather than UBI 8 appstream
  images/manageiq-base/Dockerfile
Labels: dependencies, lasker/yes

#725 Move to CentOS Stream
  images/manageiq-base/Dockerfile
Labels: enhancement

#727 no longer cache oidc_login pages
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Labels: bug

#728 Expand LimitRequestFieldSize in the internal httpd
  images/manageiq-ui-worker/container-assets/manageiq-http.conf
Labels: bug, lasker/yes?

#726 Changes for s390x + added python3-ovirt-engine rpm for s390x
  images/manageiq-base/Dockerfile
Labels: enhancement, unmergeable
