Repository ManageIQ/manageiq-pods, pull requests merged in 2021-11, with the labels that each got.

#768 Enable SSL on the API and UI pods when certificates exist
  manageiq-operator/pkg/helpers/miq-components/application.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Labels: enhancement

#772 Add a tool for generating certificates to enable SSL/TLS between pods
  .gitignore
  tools/cert_generator.rb
Labels: enhancement

#773 Remove subscription-manager
  images/manageiq-base/Dockerfile
  images/manageiq-webserver-worker/Dockerfile
Labels: bug, morphy/yes?

#774 [MORPHY] Remove subscription manager
  images/manageiq-base/Dockerfile
  images/manageiq-webserver-worker/Dockerfile
Labels: bug

#766 Remove ovirt-release repo
  images/manageiq-base/Dockerfile
Labels: technical debt
