Repository ManageIQ/manageiq-pods, pull requests merged in 2021-03, with the labels that each got.

#682 Ensure images and operator dirs are relative to the base dir
  bin/build
Labels: bug

#690 Newer versions of podman won't copy from an empty directory
  images/manageiq-base-worker/container-assets/extract-vmware-vddk
Labels: bug, images

#692 If there is a HttpdAuthConfig, add the backup label to it
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: bug, kasparov/yes?, lasker/yes?

#694 Disable gems when escaping for URL
  images/manageiq-base/container-assets/container_env
Labels: lasker/yes?, performance

#693 Move from module mod_auth_kerb to mod_auth_gssapi
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Labels: bug

#702 Clear caches better for smaller images
  images/manageiq-base-worker/Dockerfile
  images/manageiq-base/Dockerfile
  images/manageiq-orchestrator/Dockerfile
  images/manageiq-ui-worker/Dockerfile
  images/manageiq-webserver-worker/Dockerfile
Labels: performance

#703 This wasn't logging to stdout and we don't need the files
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Labels: enhancement, lasker/yes?

#704 Name the stage for easier reference
  images/manageiq-base/Dockerfile
Labels: enhancement
