Repository ManageIQ/manageiq-pods, pull requests merged in 2021-09, with the labels that each got.

#713 Initial pass at CR migrations
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/manifests/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/go.sum
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
  manageiq-operator/pkg/helpers/cr_migration/20210503163000_initial_migration.go
  manageiq-operator/pkg/helpers/cr_migration/20210504113000_migrate_image_names.go
  manageiq-operator/pkg/helpers/cr_migration/cr_migration.go
  manageiq-operator/pkg/helpers/miq-components/cr.go
  manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Labels: enhancement, morphy/yes?

#747 Switch to memcached:1 tag
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/manifests/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/helpers/miq-components/cr.go
Labels: enhancement, dependencies

#749 [MORPHY] Omit any empty fields in the ManageIQSpec
  manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
  manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go
Labels: enhancement, cleanup

#750 Add spec to check go mod tidy
  .travis.yml
  lib/tasks/spec.rake
  spec/manageiq-operator/formatting_spec.rb
  spec/manageiq-operator/gofmt_spec.rb
Labels: test

#752 [MORPHY] Partial backport of #742
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Labels: enhancement

#753 Fix more escaping issues
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Labels: bug, morphy/yes
