Repository ManageIQ/manageiq-pods, pull requests merged in 2022-02, with the labels that each got.

#812 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
Labels: test

#813 Bump ubi to 8.5
  images/manageiq-base/Dockerfile
Labels: enhancement, najdorf/yes?

#815 Document steps for operator to deploy custom images
  manageiq-operator/README.md
Labels: documentation

#816 Upgrade go to v1.17
  .github/workflows/ci.yaml
  manageiq-operator/go.mod
  manageiq-operator/go.sum
  spec/manageiq-operator/formatting_spec.rb
Labels: dependencies

#783 update node version
  images/manageiq-base/Dockerfile
Labels: dependencies

#819 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
