Repository ManageIQ/manageiq-pods, pull requests merged in 2022-05, with the labels that each got.

#836 Handle a missing database in orchestrator entrypoint
  images/manageiq-orchestrator/container-assets/entrypoint
Labels: enhancement, najdorf/yes?

#823 adding secure headers to apache
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Labels: bug, najdorf/yes

#837 Don't remove subscription-manager on s390x
  images/manageiq-base/Dockerfile
Labels: bug
