Repository ManageIQ/manageiq-pods, pull requests merged in 2022-08, with the labels that each got.

#860 Fix core apigroup definition issues
  manageiq-operator/config/rbac/role.yaml
  manageiq-operator/controllers/manageiq_controller.go
  spec/manageiq-operator/crd_spec.rb
Labels: technical debt

#861 Rely on make docker-build for consistency
  bin/build
  manageiq-operator/Makefile
Labels: bug

#863 Use bash -c to pass the environment variable
  bin/build
Labels: bug

#865 Fix issues with podman builds and docker format
  bin/build
  manageiq-operator/Makefile
Labels: bug

#866 Makefile needs shell to run shell commands
  manageiq-operator/Makefile
Labels: bug

#870 Add sensible defaults for DATABASE_URL when env vars do not exist
  images/manageiq-base/container-assets/container_env
Labels: enhancement, najdorf/yes?

#871 Simplify DATABASE_URL generation
  images/manageiq-base/container-assets/container_env
Labels: performance

#872 Check for the presence of the certs before calling update-ca-trust
  images/manageiq-base/container-assets/container_env
Labels: performance

#876 Fix file paths after operator-sdk upgrade
  lib/tasks/release.rake
Labels: bug

#874 Add app label to the operator pod
  manageiq-operator/api/v1alpha1/helpers/miq-components/operator.go
Labels: enhancement

#878 Automate updating operator go dependencies
  .github/workflows/go_dependencies.yaml
Labels: dependencies

#877 Fix make manifests
  manageiq-operator/Makefile
  manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
  spec/manageiq-operator/crd_spec.rb
Labels: bug

#879 Switch to UBI 8 minimal
  manageiq-operator/Dockerfile
Labels: oparin/yes

#882 Weekly dependency update
  manageiq-operator/go.mod
  manageiq-operator/go.sum
Labels: dependencies

#884 No need to set GOOS, it can take the value from the build environment
  manageiq-operator/Dockerfile
Labels: bug, oparin/yes
