Repository ManageIQ/manageiq-pods, pull requests merged in 2022-01, with the labels that each got.

#778 Upgrade to operator-sdk & api version 0.18
  .travis.yml
  manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/deploy/olm-catalog/manageiq-operator/manifests/manageiq.org_manageiqs_crd.yaml
  manageiq-operator/go.mod
  manageiq-operator/go.sum
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: enhancement, morphy/yes?

#785 Also remove the dnf plugin for subscription-manager
  images/manageiq-base/Dockerfile
Labels: cleanup

#787 We switched from using extensions to networking ingresses
  manageiq-operator/deploy/olm-catalog/manageiq-operator/manifests/manageiq-operator.clusterserviceversion.yaml
  manageiq-operator/deploy/role.yaml
Labels: bug, morphy/yes?

#788 Fix Httpd reconcile
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: bug

#791 gofmt -w manageiq-operator
  Gemfile
  manageiq-operator/pkg/helpers/miq-components/httpd.go
Labels: test

#790 Pull httpd from UBI (not CentOS) Appstream repo
  images/manageiq-base/Dockerfile
Labels: enhancement

#811 Fix whitesource config files
  .whitesource
Labels: cleanup
