Repository ManageIQ/manageiq-pods, pull requests merged in 2022-07, with the labels that each got.

#843 Add timeout-minutes to setup-ruby job
  .github/workflows/ci.yaml
Labels: developer

#845 Simplify bin/build to default BASE_DIR and REPO
  bin/build
Labels: enhancement

#844 Clean more files after dnf installing
  images/manageiq-base-worker/Dockerfile
  images/manageiq-base/Dockerfile
  images/manageiq-base/container-assets/clean_dnf_rpm
  images/manageiq-orchestrator/Dockerfile
  images/manageiq-ui-worker/Dockerfile
  images/manageiq-webserver-worker/Dockerfile
Labels: performance

#846 Avoid installing weak dependencies
  images/manageiq-base/Dockerfile
  images/manageiq-webserver-worker/Dockerfile
Labels: technical debt, dependencies

#859 OPERATOR_NAME is no longer used
  manageiq-operator/config/manager/manager.yaml
Labels: cleanup
