Repository ManageIQ/manageiq-pods, pull requests merged in 2022-10, with the labels that each got.

#898 Upgrade dependencies and operator-sdk
  manageiq-operator/Makefile
  manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
  manageiq-operator/config/default/manager_auth_proxy_patch.yaml
  manageiq-operator/go.mod
  manageiq-operator/go.sum
  spec/manageiq-operator/crd_spec.rb
Labels: dependencies

#888 Upgrade to UBI9 memcached image with memcached v1.6.9
  manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go
  manageiq-operator/api/v1alpha1/manageiq_types.go
  manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
Labels: dependencies

#889 Add a build action
  .github/workflows/build_pods.yaml
Labels: developer

#907 Revert back to UBI8 for now.
  manageiq-operator/Dockerfile
Labels: dependencies

#910 [Morphy] update protobuf & crypto
  .travis.yml
  manageiq-operator/go.mod
  manageiq-operator/go.sum
  spec/spec_helper.rb
Labels: dependencies

#906 Remove manageiq-appliance-build clone and customization hook
  README.md
  bin/build
  images/manageiq-base/Dockerfile
Labels: technical debt

#909 Follow operator-sdk upgrade guide for v1.25
  manageiq-operator/Makefile
Labels: dependencies
