Repository ManageIQ/manageiq-pods, pull requests merged in 2022-09, with the labels that each got.

#885 Add back labels from before the operator-sdk upgrade
  manageiq-operator/Dockerfile
Labels: oparin/yes

#886 go get -t -u && go mod tidy
  manageiq-operator/go.mod
  manageiq-operator/go.sum
Labels: dependencies

#883 Use podman if available, fall back to docker
  bin/build
  manageiq-operator/Makefile
Labels: bug

#887 Upgrade the operator image to UBI 9
  manageiq-operator/Dockerfile
Labels: dependencies

#890 [MORPHY] update golang
  manageiq-operator/go.mod
  manageiq-operator/go.sum
Labels: dependencies, security vulnerability

#891 Enable ruby 3 for building images
  images/manageiq-base/Dockerfile
Labels: ruby3

#895 Fix default Kafka secret
  manageiq-operator/api/v1alpha1/helpers/miq-components/kafka.go
Labels: bug

#894 Add Zookeeper network policy
  manageiq-operator/api/v1alpha1/helpers/miq-components/network_policies.go
  manageiq-operator/controllers/manageiq_controller.go
Labels: enhancement
