Repository ManageIQ/manageiq-pods, pull requests merged in 2022-03, with the labels that each got.

#821 Add watch for network policies
  manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
Labels: bug, najdorf/yes?

#822 set oidc cookies to use same site
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Labels: bug, najdorf/yes?

#825 Allow httpGet health probes using the /ping endpoint
  images/manageiq-webserver-worker/Dockerfile
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Labels: enhancement

#826 Fix escaping
  manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Labels: bug

#827 Upgrade crypto package 🤷🏻 🧨 🚽
  manageiq-operator/go.mod
  manageiq-operator/go.sum
Labels: dependencies

#828 Upgrade more indirect dependencies 🤷🏻
  manageiq-operator/go.mod
  manageiq-operator/go.sum
Labels: dependencies
