Repository ManageIQ/manageiq-pods, pull requests merged in 2023-10, with the labels that each got.

#999 Add permissions for pods/logs to the manageiq-automation role
  manageiq-operator/api/v1alpha1/helpers/miq-components/rbac.go
Labels: bug, quinteros/yes

#1000 Give the operator permission to give permission to pod/logs get
  manageiq-operator/config/rbac/role.yaml
  manageiq-operator/internal/controller/manageiq_controller.go
Labels: bug, quinteros/yes

#1001 Fix typo pods/log
  manageiq-operator/api/v1alpha1/helpers/miq-components/rbac.go
  manageiq-operator/config/rbac/role.yaml
  manageiq-operator/internal/controller/manageiq_controller.go
Labels: bug, quinteros/yes

#1003 Add Node affinity
  manageiq-operator/api/v1alpha1/helpers/miq-components/httpd.go
  manageiq-operator/api/v1alpha1/helpers/miq-components/kafka.go
  manageiq-operator/api/v1alpha1/helpers/miq-components/memcached.go
  manageiq-operator/api/v1alpha1/helpers/miq-components/operator.go
  manageiq-operator/api/v1alpha1/helpers/miq-components/orchestrator.go
  manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql.go
  manageiq-operator/api/v1alpha1/miqutils/find.go
  manageiq-operator/api/v1alpha1/miqutils/node_affinity.go
  manageiq-operator/config/manager/manager.yaml
  manageiq-operator/internal/controller/manageiq_controller.go
Labels: enhancement, quinteros/yes?

#1007 Drop Ruby 2.7
  .github/workflows/ci.yaml
Labels: ruby3
