Repository ManageIQ/manageiq-pods, pull requests merged in 2023-04, with the labels that each got.

#956 Ensure latest samba is installed
  images/manageiq-base/Dockerfile
Labels: enhancement, dependencies

#936 Upsize default Kafka volume capacity
  manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go
Labels: bug

#958 Install httpd after replacing the release RPM
  images/manageiq-base/Dockerfile
Labels: bug, dependencies, petrosian/yes
