Repository ManageIQ/manageiq-pods, pull requests merged in 2023-06, with the labels that each got.

#968 Log to stderr by turning off the log file collector
  manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql_conf.go
Labels: bug, petrosian/yes?

#970 Allow workflow_dispatch GHA event
  .github/workflows/ci.yaml
Labels: test, petrosian/yes

#971 Mark deprecated spec properties.
  manageiq-operator/api/v1alpha1/manageiq_types.go
  manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
Labels: technical debt

#972 [petrosian] Mark deprecated spec properties.
  manageiq-operator/api/v1alpha1/manageiq_types.go
  manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
Labels: technical debt

#974 Let sysv handle dynamic shared memory type for containers
  manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql_conf.go
Labels: bug, petrosian/yes

#975 Add a test to ensure that go versions are all the same
  spec/manageiq-operator/go_version_spec.rb
Labels: enhancement

#976 [Morphy] Update dependencies
  manageiq-operator/go.mod
  manageiq-operator/go.sum
  manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go
Labels: dependencies
