Repository ManageIQ/manageiq-pods, pull requests merged in 2023-02, with the labels that each got.

#932 Ensure that ManageAppSecret is managing the app secret
  manageiq-operator/api/v1alpha1/helpers/miq-components/app-secret.go
Labels: bug

#935 Allow Kafka communications
  manageiq-operator/api/v1alpha1/helpers/miq-components/kafka.go
  manageiq-operator/api/v1alpha1/helpers/miq-components/network_policies.go
  manageiq-operator/controllers/manageiq_controller.go
Labels: enhancement

#914 Upgrade Go
  .github/workflows/ci.yaml
  manageiq-operator/api/v1alpha1/groupversion_info.go
  manageiq-operator/go.mod
Labels: dependencies, oparin/no, petrosian/yes?

#938 Followup to #930
  images/manageiq-base/Dockerfile
  images/manageiq-base/container-assets/container_env
Labels: refactoring
