Repository ManageIQ/manageiq-pods, pull requests merged in 2024-11, with the labels that each got.

#1184 Switch to ruby 3.3
  .github/workflows/ci.yaml
  images/manageiq-base/Dockerfile
Labels: enhancement

#1186 [quinteros] Lock down to ruby 3.0.4 from Appstream
  images/manageiq-base/Dockerfile
Labels: bug

#1185 go get -t -u ./... && go mod tidy
  manageiq-operator/go.mod
  manageiq-operator/go.sum
Labels: dependencies, radjabov/yes?

#1155 CP4AIOPS-3113 pass delimiter for groups
  manageiq-operator/api/v1alpha1/helpers/miq-components/httpd_conf.go
Labels: bug
