Repository ManageIQ/manageiq-pods, pull requests merged in 2024-03, with the labels that each got.

#1068 Update CI to use Ruby 3.1
  .github/workflows/ci.yaml
Labels: dependencies

#1029 Upgrade to ginkgo v2
  manageiq-operator/go.mod
  manageiq-operator/go.sum
  manageiq-operator/internal/controller/suite_test.go
Labels: dependencies

#1069 Reorder DB container_env values for readability
  images/manageiq-base/container-assets/container_env
Labels: cleanup

#1065 Move RPM copying into a separate image
  .gitignore
  bin/build
  images/manageiq-base/Dockerfile
  images/manageiq-base/container-assets/prepare_local_yum_repo.sh
  images/manageiq-rpms/Dockerfile
  images/manageiq-rpms/rpms/.gitkeep
  images/manageiq-webserver-worker/Dockerfile
Labels: enhancement

#1070 Drop MAINTAINER docker commands
  images/manageiq-base-worker/Dockerfile
  images/manageiq-base/Dockerfile
  images/manageiq-orchestrator/Dockerfile
  images/manageiq-ui-worker/Dockerfile
  images/manageiq-webserver-worker/Dockerfile
Labels: technical debt

#1071 Fix the manifest generation by allowing it to see the local rpms
  images/manageiq-base/Dockerfile
  images/manageiq-webserver-worker/Dockerfile
Labels: bug

#1067 Updates for OpenTofu runner
  manageiq-operator/api/v1alpha1/helpers/miq-components/orchestrator.go
  manageiq-operator/api/v1alpha1/manageiq_types.go
  manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
Labels: enhancement

#1078 Upgrade to operator-sdk v1.34.1
  bin/before_install
  manageiq-operator/Makefile
  manageiq-operator/go.mod
  manageiq-operator/go.sum
Labels: dependencies, radjabov/yes?
