Repository ManageIQ/manageiq-pods, pull requests merged in 2024-08, with the labels that each got.

#1148 Update go to v1.23
  manageiq-operator/Dockerfile
  manageiq-operator/go.mod
Labels: dependencies

#1150 Update go dependencies and operator-sdk
  manageiq-operator/Makefile
  manageiq-operator/config/default/manager_auth_proxy_patch.yaml
  manageiq-operator/go.mod
  manageiq-operator/go.sum
  spec/manageiq-operator/go_version_spec.rb
Labels: dependencies, radjabov/yes?

#1151 Make the sed line Mac compatible
  manageiq-operator/Makefile
Labels: bug, radjabov/yes?

#1154 Upgrade to dumb-init 1.2.5
  images/manageiq-base/Dockerfile
Labels: dependencies

#1157 Default the system password_encryption to scram-sha-256
  manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql_conf.go
Labels: enhancement, radjabov/yes?

#1161 If routes are available, prefer them and use cluster default certificate
  manageiq-operator/api/v1alpha1/helpers/miq-components/httpd.go
  manageiq-operator/internal/controller/manageiq_controller.go
Labels: enhancement
