Repository ManageIQ/manageiq-pods, pull requests merged in 2024-01, with the labels that each got.

#896 Enforce and default Kafka configuration
  images/manageiq-orchestrator/container-assets/entrypoint
  manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go
  manageiq-operator/api/v1alpha1/manageiq_types.go
  manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
Labels: enhancement, quinteros/yes?

#1024 Deploy messaging by default
  images/manageiq-orchestrator/container-assets/entrypoint
  manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go
Labels: enhancement

#1005 Replace Bitnami with Strimzi Kafka
  manageiq-operator/api/v1alpha1/helpers/miq-components/kafka.go
  manageiq-operator/api/v1alpha1/helpers/miq-components/kafka/kafka.go
  manageiq-operator/api/v1alpha1/helpers/miq-components/network_policies.go
  manageiq-operator/api/v1alpha1/helpers/miq-components/orchestrator.go
  manageiq-operator/api/v1alpha1/miqutils/find.go
  manageiq-operator/api/v1alpha1/miqutils/node_affinity.go
  manageiq-operator/cmd/main.go
  manageiq-operator/config/rbac/role.yaml
  manageiq-operator/go.mod
  manageiq-operator/go.sum
  manageiq-operator/internal/controller/manageiq_controller.go
Labels: enhancement, quinteros/yes?

#1025 Bump strimzi to 0.37
  manageiq-operator/api/v1alpha1/helpers/miq-components/kafka/kafka.go
Labels: enhancement, quinteros/yes?

#1026 Revert default messaging change
  images/manageiq-orchestrator/container-assets/entrypoint
  manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go
Labels: bug, quinteros/yes?

#1027 Upgrade to operator-sdk v1.33
  manageiq-operator/PROJECT
  manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql.go
  manageiq-operator/go.mod
  manageiq-operator/go.sum
Labels: dependencies, quinteros/yes?

#1031 Change renovate to do a go mody tidy as part of the update
  renovate.json
Labels: test

#1038 Upgrade to ruby 3.1
  images/manageiq-base/Dockerfile
Labels: enhancement, dependencies, ruby3

#1040 Drop Issue/PR templates after merge of ManageIQ/.github#7
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: technical debt

#1044 Error handling for FindCatalogSourceByName
  manageiq-operator/api/v1alpha1/miqutils/find.go
Labels: bug, quinteros/yes?
