Repository ManageIQ/manageiq-pods, pull requests merged in 2024-09, with the labels that each got.

#1165 Restart pods on certificate renewal
  manageiq-operator/api/v1alpha1/helpers/miq-components/orchestrator.go
  manageiq-operator/api/v1alpha1/helpers/miq-components/util.go
  manageiq-operator/internal/controller/manageiq_controller.go
Labels: enhancement, radjabov/yes?

#1167 Fix issue with pass-by-reference
  manageiq-operator/api/v1alpha1/helpers/miq-components/orchestrator.go
  manageiq-operator/api/v1alpha1/helpers/miq-components/util.go
Labels: bug, radjabov/yes

#1169 Watch routes and ingress, ensure we're only using one
  manageiq-operator/api/v1alpha1/helpers/miq-components/httpd.go
  manageiq-operator/internal/controller/manageiq_controller.go
Labels: bug, radjabov/yes?
